import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarClock, Mail, MessagesSquare, NotebookPen, ShieldCheck, Telescope } from "lucide-react";
import { PageHeader, PageShell } from "@/components/AppShell";

const title = "Synthetix — AI Workplace Productivity Assistant";
const description =
  "A clean AI workspace for professionals: generate emails, summarize meetings, plan your week, research topics and chat with an assistant.";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title },
      { name: "description", content: description },
      { property: "og:title", content: title },
      { property: "og:description", content: description },
    ],
  }),
  component: Dashboard,
});

const TOOL_CARDS = [
  {
    to: "/email",
    icon: Mail,
    name: "Smart Email Generator",
    copy: "Draft professional correspondence with targeted intent and specific tone control.",
  },
  {
    to: "/notes",
    icon: NotebookPen,
    name: "Meeting Notes Summarizer",
    copy: "Convert lengthy transcripts into decisions, owners, deadlines and action items.",
  },
  {
    to: "/planner",
    icon: CalendarClock,
    name: "AI Task Planner",
    copy: "Turn a backlog into a prioritized, time-blocked daily or weekly schedule.",
  },
  {
    to: "/research",
    icon: Telescope,
    name: "AI Research Assistant",
    copy: "Summarize topics or pasted articles into insights and ranked recommendations.",
  },
  {
    to: "/chat",
    icon: MessagesSquare,
    name: "AI Chatbot",
    copy: "Talk through work problems with a conversational assistant that keeps context.",
  },
] as const;

const PRINCIPLES = [
  {
    heading: "Human in the loop",
    copy: "Every output is editable before it leaves the workspace. Nothing is sent on your behalf.",
  },
  {
    heading: "Transparent limits",
    copy: "The assistant marks missing facts as placeholders and flags what it cannot verify.",
  },
  {
    heading: "Data minimisation",
    copy: "Nothing you type is stored on a server. Avoid entering confidential or personal data.",
  },
];

function Dashboard() {
  return (
    <PageShell>
      <PageHeader
        title="AI Workplace Productivity Assistant"
        blurb="Select a specialized utility to accelerate your daily operational workflow. Every tool uses a structured prompt and returns an editable draft."
      />

      <div className="mb-20 grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">
        {TOOL_CARDS.map(({ to, icon: Icon, name, copy }) => (
          <Link
            key={to}
            to={to}
            className="group rounded-xl bg-elevated p-6 ring-1 ring-border transition-colors hover:bg-accent/40"
          >
            <div className="mb-4 grid size-8 place-items-center rounded bg-muted">
              <Icon className="size-4" strokeWidth={1.75} />
            </div>
            <h2 className="mb-2 font-medium">{name}</h2>
            <p className="max-w-[40ch] text-sm text-muted-foreground">{copy}</p>
          </Link>
        ))}
      </div>

      <section className="border-t border-border pt-12">
        <div className="mb-6 flex items-center gap-3">
          <ShieldCheck className="size-5" strokeWidth={1.6} />
          <h2 className="text-xl font-medium tracking-tight">Responsible AI practices</h2>
        </div>
        <div className="grid gap-5 md:grid-cols-3">
          {PRINCIPLES.map((p) => (
            <div key={p.heading} className="rounded-xl bg-muted/40 p-5 ring-1 ring-border">
              <h3 className="mb-2 text-sm font-medium">{p.heading}</h3>
              <p className="text-sm text-muted-foreground">{p.copy}</p>
            </div>
          ))}
        </div>
        <p className="mt-6 max-w-[70ch] text-[11px] leading-relaxed text-muted-foreground">
          Disclaimer: outputs are generated by AI and may be inaccurate, biased or incomplete. They are not legal,
          medical, financial or HR advice. Review and verify all content before using it in a professional setting.
        </p>
      </section>
    </PageShell>
  );
}
